name: stress_sense
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.0.0
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  google_sign_in: ^6.2.1
  flutter_signin_button: ^2.0.0
  fl_chart: ^0.66.0
  flutter_blue_plus: ^1.31.8
  permission_handler: ^11.3.1
  http: ^1.6.0
  cloud_firestore: ^6.1.1
  cristalyse: ^1.17.2
  form_field_validator: ^1.1.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  connectivity_plus: ^6.1.3
  internet_connection_checker: ^3.0.1
  intl: ^0.20.2
  lottie: ^3.3.1
  shared_preferences: ^2.5.2
  dartz: ^0.10.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/lotties/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic